### ISSUE TITLE
[feature] more complex HPAs

### ISSUE THREAD

**Issue by zswanson** [second-front/uchart#21]
Need more access to the hpa v2 spec, such as Behavior to tune scale in/out. 
Also can we query a prometheus metrics adapter for external metrics type? 
If so we need to be able to specify different metric types.

**Comment by drduker** [comment]
Done - https://github.com/second-front/uchart/commit/dc296c7de2af4f362faff3911754513c54134a81

**Comment by drduker** [comment]
fixed to include external in 1.0.17
