### ISSUE TITLE
Create a common template for pod definiton

### ISSUE THREAD

**Issue by kamilkrampa** [second-front/uchart#29]
Currently, we're copying and pasting the pod definition between different resources. We could create a pod definition template and include it in all resources that contain a pod definition.

It's a very common practice [example](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl)

**Comment by KacperLegowski** [comment]
@drduker are you planning to implement this?

**Comment by drduker** [comment]
still planned yes, is there something you are missing right now?

**Comment by drduker** [comment]
Created the pod template branch.  Just need to fully test everything.  Satisfying to remove all the duplicate template lines.
https://github.com/second-front/uchart/blob/pod-template/templates/_pod.tpl

**Comment by drduker** [comment]
Done and merged.  Added to 1.0.12 tag - https://github.com/second-front/uchart/commit/eb22edee8a3ce16cef4683dbf9a83028d6b460d8

Tested locally, still need to test with live apps tomorrow for anything missed with the bigger change here.
