### ISSUE TITLE
chart defaults for container security context are overwritten rather than merged

### ISSUE THREAD

**Issue by zswanson** [second-front/uchart#38]
I'm assuming you wanted security defaults for 'runAsNonRoot' etc to _always_ be set, but they are instead overwritten when I go to add the runAsUser fields to satisfy the nonRoot condition.

**Comment by drduker** [comment]
are you using the lastest - 1.0.23?

**Comment by drduker** [comment]
nm, i was able to reproduce

**Comment by drduker** [comment]
fixed in uchart:1.0.24
